language: php

php: 
  - 5.5.9

before_script:
  #create environment file
  - cp ./.env.example ./.env 
  # Install latest composer
  - curl -s http://getcomposer.org/installer | php
  #Install Project
  - php composer.phar install
  #generate Application key
  - php artisan key:generate 

script: phpunit