language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  

 before_script:
  - cp ./.env.example ./.env
  #create environment file
  - curl -s http://getcomposer.org/installer | php
  #Install latest composer
  - php composer.phar install
  #Install project
  - php artisan key:generate 
  generate Application key
  
  
#Unit testing  
script: phpunit

branches:
  only:
  - master