language: php

php:
  - 5.5
  - 5.6

before_script:
 #Download and install the latest composer
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install
 
 #Install Code Coverage, https://github.com/satooshi/php-coveralls
 - php composer.phar require "satooshi/php-coveralls:dev-master"
 
 #Install PHP CodeSniffer for Laravel, https://github.com/antonioribeiro/laravelcs
 - php composer.phar require "pragmarx/laravelcs"
 
 #Install PHP Copy/Paste Detector, https://github.com/sebastianbergmann/phpcpd
 - php composer.phar require "sebastian/phpcpd=*"
 
 #Install PHP Mess  Detector, https://github.com/phpmd/phpmd
 - php composer.phar require "phpmd/phpmd:@stable"
 
 #Install PHPLOC 
 - php composer.phar require "phploc/phploc=*"
 
 #create environment file
 - cp ./.env.example ./.env
 #generate Application key
 - php artisan key:generate

script:
 #Run PHPUnit with Coverage
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml
 
 #Run PHP CodeSniffer for Laravel
 #- vendor/bin/phpcs --standard=vendor/pragmarx/laravelcs/Standards/Laravel/ app/
 
 #Run PHP Copy/Paste Detector in folder "app"
 - vendor/bin/phpcpd --verbose app/
 
 # Run PHP Mess Detector in folder "app"
 #- vendor/bin/phpmd app/ text vendor/phpmd/phpmd/src/main/resources/rulesets/cleancode.xml
 - vendor/bin/phpmd app/ text vendor/phpmd/phpmd/src/main/resources/rulesets/codesize.xml	 
 - vendor/bin/phpmd app/ text vendor/phpmd/phpmd/src/main/resources/rulesets/controversial.xml
 - vendor/bin/phpmd app/ text vendor/phpmd/phpmd/src/main/resources/rulesets/design.xml
 #- vendor/bin/phpmd app/ text vendor/phpmd/phpmd/src/main/resources/rulesets/naming.xml
 - vendor/bin/phpmd app/ text vendor/phpmd/phpmd/src/main/resources/rulesets/unusedcode.xml
 
 #Run PHPLoc for folder "app"
 - vendor/phploc/phploc/phploc app/ --log-xml=build/logs/phploc.xml
 
 #Run LINT 
 - find app/ -type f -name \*.php -exec php -l {} \;|grep -v 'No syntax error'
 
after_script:
 - php vendor/bin/coveralls -v