language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
#create environment file, Install latest composer, Install project, generate Application key
before_script:
  - cp ./.env.example ./.env 
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - php artisan key:generate 

script: phpunit