# Set up notification options
notifications: 
  email:
    recipients:
      - lukacsbarni@gmail.com
      - blukacs@pentalog.fr
    #change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

# specify language
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# configure which branches to run
branches:
  # whitelist
  only:
    - master
    - /^deploy-.*$/ # regex ok
  # blacklist
  except:
    - dontrunme 
    - test  

## begin build steps
####################
before_script:
  #create environment file
  - cp ./.env.example ./.env
  #Install latest composer
  - curl -s http://getcomposer.org/installer | php
  #Install Project
  - php composer.phar install
  #generate Application key
  - php artisan key:generate
  - echo "MVN version"
  - mvn -version
  
#Unit testing  
script: phpunit